
services:
  reverse-proxy:
    image: nginx:latest
    container_name: hpc-proxy
    ports:
      - "5051:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - frontend
    networks:
      - slurm-hpc-network

  frontend:
    build: ./frontend
    image: adeelumar17/hpc-slurm-frontend:latest
    container_name: hpc-slurm-frontend
    expose:
      - "5051"
    networks:
      - slurm-hpc-network
    restart: always

  backend:
    build: ./backend
    image: adeelumar17/hpc-slurm-backend:latest
    container_name: hpc-slurm-backend
    network_mode: host
    env_file:
      - ./backend/.env
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: hpc-grafana
    user: "472:472"   # ← Add this line to avoid permission errors
    ports:
      - "3000:3000"   # Optional: expose for direct access during setup
    volumes:
      - ./grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin   # Change later
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - slurm-hpc-network
    restart: always
    # depends_on:
      # - backend
      
networks:
  slurm-hpc-network:
    driver: bridge

